### ISSUE TITLE
audplot.scatter limits axis wrongly for some input data

### ISSUE THREAD

**Issue by hagenw** [audeering/audplot#11]
We have the following two lines in `audplot.scater`:
https://github.com/audeering/audplot/blob/da1279fea2ba0bd65eaed9eee985a9028239c3c0/audplot/core/api.py#L211-L212

But as input type we allow:
https://github.com/audeering/audplot/blob/da1279fea2ba0bd65eaed9eee985a9028239c3c0/audplot/core/api.py#L183-L184

For tuples as input it will fail due to the `+`, and for `Series` it will not fail but return the maximum value after performing an addition between the truth and prediction values.

**Comment by frankenjoe** [comment]
Good observation. Maybe we could always convert to a `pd.Series` first and then use `pd.concat()` on the result instead of `+`.

**Comment by frankenjoe** [comment]
Btw: we do the same in `audplot.series()`, so I think we need to fix it there, too.

**Comment by frankenjoe** [comment]
Or we simply do not set the `y` limit and let the user take care of it?

**Comment by frankenjoe** [comment]
Just realized that in case of `scatter` we need `minimum` and `maximum` if to draw the diagonal.
