### ISSUE TITLE
Publishing fails due too huge doc dependencies

### ISSUE THREAD

**Issue by hagenw** [audeering/audplot#32]
For the latest 1.3.0 release building and publishing the documentation failed while installing `numba`:

https://github.com/audeering/audplot/runs/4089683259?check_suite_focus=true

I'm not sure why it tried to install it in the first place, maybe due to our `librosa` dependency?

**Comment by hagenw** [comment]
So maybe we should just store the trumpet example files as part of the repo and delete the `librosa` dependency?

**Comment by hagenw** [comment]
There are two possible solutions:
* we include the mono version of the trumpet sound as part of the `audplot` package (it is 27K in size and has a CC-BY license), see https://github.com/librosa/data/tree/main/audio. Then we still have to think about loading it silently inside the plot examples, or if we need to provide a function to load the example.
* we download the trumpet sample from the Github URL (https://github.com/librosa/data/raw/main/audio/sorohanro_-_solo-trumpet-06.ogg) as [librosa is doing it](https://github.com/librosa/librosa/blob/9198e00b5d16e06f5895cc61a11d42a96c7fecb8/librosa/util/files.py#L43-L100). The downside is that we maybe have to handle caching it then to avoid downloading it all the time?
*

**Comment by hagenw** [comment]
I just realize, we also use `librosa.feature.mfcc(x, sr)` in the examples. So maybe we should stick with `librosa` but look if we can avoid that the installation of it fails on Github?

**Comment by frankenjoe** [comment]
> For the latest 1.3.0 release building and publishing the documentation failed while installing `numba`

Why wasn't it failing before?

**Comment by hagenw** [comment]
Because we have a non-deterministic Python version in our publishing script (at least my guess), compare https://github.com/audeering/audplot/pull/33
