### ISSUE TITLE
Bars in distrubtion plot not consistent

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audplot#34]
In the following example the bars of `Truth` are not consistently visualized:

```python
import matplotlib.pyplot as plt
import numpy as np

import audplot


np.random.seed(0)

N = 1000

truth = np.random.normal(-0.25, 1.0, N)
p1 = np.random.uniform(0.25, 1.0, N)
p2 = np.random.uniform(0.25, 1.0, N)

fig, axs = plt.subplots(1, 2)

audplot.distribution(truth, p1, ax=axs[0])
audplot.distribution(truth, p2, ax=axs[1])
plt.show()
```

![image](https://user-images.githubusercontent.com/10383417/141948656-f4b34151-2dfe-4650-bbb9-d954bccbda40.png)

**Comment by frankenjoe** [comment]
With `v1.2.0` it still worked:

![image](https://user-images.githubusercontent.com/10383417/141948994-d9c722c5-c17f-4cc8-b08e-eab26d999392.png)

**Comment by hagenw** [comment]
I would say this is a feature/bug of `seaborn.histplot`

**Comment by hagenw** [comment]
In https://stackoverflow.com/q/68865538 they proposed to use `common_bins=False` with `seaborn.histplot` to fix this.

**Comment by frankenjoe** [comment]
> In https://stackoverflow.com/q/68865538 they propose to use `common_bins=False` with `seaborn.histplot` to fix this.

![image](https://user-images.githubusercontent.com/10383417/141951352-bc1077c0-d421-45f3-bf1a-b009cdbe27d6.png)

Mhh..

**Comment by frankenjoe** [comment]
Setting`stat='density'`in addition seems to solve the problem:

![image](https://user-images.githubusercontent.com/10383417/141951856-041595c6-69e7-415b-ba25-c535ee49b09b.png)

**Comment by frankenjoe** [comment]
Only that the outline of `Prediction` looks a bit odd now.

**Comment by hagenw** [comment]
This happens, because the KDE line is calculated also independently for the different distributions. There is a parameter that affects how far the curve should extend beyond the actual distribution boundaries, e.g.

```python
kde_kws={'cut': 2}
```

the problem is that this is applied to all distributions and hence extends the x-axis

![kde](https://user-images.githubusercontent.com/173624/141954790-1911c855-bd67-4041-b47a-67f82932df74.png)

So maybe we just life with the fact that uniform distributions are not that nicely rendered with the KDE curve.

**Comment by hagenw** [comment]
Seems like in `distplot` `cut` was set to 3

![kde2](https://user-images.githubusercontent.com/173624/141955268-cabd9536-58dc-4f40-baad-4f5dd4089082.png)

Or they had a way to automatically calculate the best value?

**Comment by hagenw** [comment]
yes, they hard coded it to `3`, see https://github.com/mwaskom/seaborn/blob/b13dfdb6570b943391f5c230b038b44d600a19a7/seaborn/distributions.py#L2671

**Comment by hagenw** [comment]
The problem when switching to `stat='density'` is that we loose the count information, which is unfortunate.

**Comment by frankenjoe** [comment]
Yes, there seems to be no best solution. I would still say it's more important we have consistent bars, otherwise it's quite confusing when you want to compare results.
