### ISSUE TITLE
No pots shown for spectrum(), signal(), cepstrum()

### ISSUE THREAD

**Issue by hagenw** [audeering/audplot#8]
On the documentation page of the API (https://audeering.github.io/audplot/api.html) the doc examples for `spectrum()`, `signal()`, and `spectrum()` do not show a figure as output.

**Comment by hagenw** [comment]
I cannot reproduce this issue locally.

**Comment by hagenw** [comment]
The figures are missing in the github pages branch at https://github.com/audeering/audplot/tree/gh-pages

Locally I have `api-2.svg`, `api-13.svg`, and `api-15.svg`

**Comment by frankenjoe** [comment]
Maybe related to the `plt.tight_layout()`, which we don't call in the other examples.

**Comment by hagenw** [comment]
The problem is that `soundfile` cannot find the sndfile library when imported by `librosa`
https://github.com/audeering/audplot/runs/3054434199?check_suite_focus=true

**Comment by hagenw** [comment]
So maybe we can mock `soundfile` as we don't need it (should be possible inside `docs/conf.py`) or add `sndfile` to the packages to install, but I would go with the first solution.

**Comment by hagenw** [comment]
On the other hand, the problem is that I don't know if `autodoc_mock_imports = ['soundfile']` is used when creating the figures, or only when using the `autodoc` extension. We can also not easily test this as we install `libsndfile1` anyway before running the tests. So, I would propose to also install it when publishing the package.
